version: "3.8"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - NODE_ENV=production
      - PORT=${PORT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - APP_DOMAIN=${APP_DOMAIN}
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "4000:4000"
    depends_on:
      - backend

volumes:
  mongo-data:
